### ISSUE TITLE
loading subunit stream from stdin with stestr load is broken

### ISSUE THREAD

**Issue by mtreinish** [mtreinish/stestr#109]
Loading a subunit stream from stdin is not working for stestr load. A simple example to reproduce this is to run::

  stestr last --subunit | stestr load

Which will yield this traceback:

Traceback (most recent call last):
  File "/home/mtreinish/.venv2/bin/stestr", line 10, in <module>
    sys.exit(main())
  File "/home/mtreinish/git/stestr/stestr/cli.py", line 102, in main
    sys.exit(args[0].func(args))
  File "/home/mtreinish/git/stestr/stestr/commands/load.py", line 75, in run
    abbreviate=args.abbreviate)
  File "/home/mtreinish/git/stestr/stestr/commands/load.py", line 128, in load
    streams = [sys.stdin.buffer]
AttributeError: 'file' object has no attribute 'buffer'

We should fix this and add a unit and/or functional test checking that load from stdin works

**Comment by mtreinish** [comment]
Looks like we just need to drop the .buffer on L128 in stestr/commands/load.py
