### ISSUE TITLE
Running 1 test with --no-discover results in an error

### ISSUE THREAD

**Issue by relaxdiego** [mtreinish/stestr#244]
### Issue description

When attempting to run a single test method in test file, as specified in the documentation, stestr errors out with the following:

```
Traceback (most recent call last):
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/bin/stestr", line 10, in <module>
    sys.exit(main())
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/stestr/cli.py", line 111, in main
    return cli.run(argv)
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/cliff/app.py", line 281, in run
    result = self.run_subcommand(remainder)
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/cliff/app.py", line 401, in run_subcommand
    result = cmd.run(parsed_args)
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/cliff/command.py", line 184, in run
    return_code = self.take_action(parsed_args) or 0
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/stestr/commands/run.py", line 213, in take_action
    suppress_attachments=suppress_attachments)
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/stestr/commands/run.py", line 366, in run_command
    return run_tests()
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/stestr/commands/run.py", line 363, in run_tests
    suppress_attachments=suppress_attachments)
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/stestr/commands/load.py", line 209, in load
    color, stdout, abbreviate, suppress_attachments)
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/stestr/commands/load.py", line 251, in _load_case
    start_time = min(start_times)
ValueError: min() arg is an empty sequence
ERROR: InvocationError: '/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/bin/stestr run --no-discover unit_tests/test_lib_charm_openstack_cinder_freenas.py::TestCinderFreeNASCharm::test_cinder_base'
```

#### Expected behavior and actual behavior

It executes successfully with the following output:

```
{0} unit_tests.test_lib_charm_openstack_cinder_freenas.TestCinderFreeNASCharm.test_cinder_base [0.001872s] ... ok

======
Totals
======
Ran: 1 tests in 0.0019 sec.
 - Passed: 1
 - Skipped: 0
 - Expected Fail: 0
 - Unexpected Success: 0
 - Failed: 0
Sum of execute time for each test: 0.0019 sec.

==============
Worker Balance
==============
 - Worker 0 (1 tests) => 0:00:00.001872
___________________________________________________________________________________________________________________________________ summary ____________________________________________________________________________________________________________________________________
  py3: commands succeeded
  congratulations :)
```

#### Steps to reproduce the problem

Run a single test as per documentation:

```
stestr run --no-discover project/tests/test_foo.py::TestFoo::test_method
```

Reference: https://stestr.readthedocs.io/en/latest/MANUAL.html#running-tests

#### Specifications like the version of the project, operating system, or hardware

```
multipass@dev:~/src/review.opendev.org/cinder-freenas$ uname -a
Linux dev 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

### System information

**stestr version (`stestr --version`):** 2.3.1

**Python release (`python --version`):** Python 3.6

**pip packages (`pip freeze`):** attrs==19.1.0,charmhelpers==0.19.13,charms.openstack==0.0.1.dev1,charms.reactive==1.2.1,cliff==2.14.1,cmd2==0.9.12,colorama==0.4.1,coverage==4.5.3,entrypoints==0.3,extras==1.0.0,fixtures==3.0.0,flake8==3.7.7,future==0.17.1,Jinja2==2.10.1,linecache2==1.0.0,MarkupSafe==1.1.1,mccabe==0.6.1,mock==3.0.5,netaddr==0.7.19,os-testr==1.0.0,pbr==5.2.1,pkg-resources==0.0.0,prettytable==0.7.2,pyaml==19.4.1,pycodestyle==2.5.0,pyflakes==2.1.1,pyparsing==2.4.0,pyperclip==1.7.0,python-mimeparse==1.6.0,python-subunit==1.3.0,PyYAML==5.1.1,six==1.12.0,stestr==2.3.1,stevedore==1.30.1,Tempita==0.5.2,testtools==2.3.0,traceback2==1.4.0,unittest2==1.1.0,voluptuous==0.11.5,wcwidth==0.1.7

### Additional information

Running an alternative command as a workaround:

```
stestr run unit_tests.test_lib_charm_openstack_cinder_freenas.TestCinderFreeNASCharm.test_cinder_base
{0} unit_tests.test_lib_charm_openstack_cinder_freenas.TestCinderFreeNASCharm.test_cinder_base [0.002587s] ... ok

======
Totals
======
Ran: 1 tests in 0.0026 sec.
 - Passed: 1
 - Skipped: 0
 - Expected Fail: 0
 - Unexpected Success: 0
 - Failed: 0
Sum of execute time for each test: 0.0026 sec.

==============
Worker Balance
==============
 - Worker 0 (1 tests) => 0:00:00.002587
___________________________________________________________________________________________________________________________________ summary ____________________________________________________________________________________________________________________________________
  py3: commands succeeded
  congratulations :)
```

However, the above is slow since stestr first needs to discover all tests before it filters it down to the one I wanted to run.

**Comment by mtreinish** [comment]
Thanks for filing this, I can confirm this is an issue, I actually hit it yesterday for the first time myself locally and was going to spend some time investigating it today.

**Comment by mtreinish** [comment]
@relaxdiego So I've been doing some local debugging on my issues. There are 2 things going on, first the `ValueError: min() arg is an empty sequence` is being caused because there are no results in the output from the test execution, I have a patch to fix that (it's relatively straightforward and I'll push it up shortly).

But it doesn't fix the underlying fault causing the lack of results. In my case in the local test suite where I was hitting this issue it was caused by a bug in testtools (well really unittest2) when running that test suite without discovery. It did raise an error from the subunit worker process when it tried to run the test specified and that's why there weren't any results. I'm thinking there might be an underlying error happening early in the test execution that's causing this for you too. Is the test suite you're running this on open so I can take a look? If not can you see if there are any other errors above the traceback you pasted here already?

**Comment by relaxdiego** [comment]
@mtreinish Thanks for the quick feedback! Below is the entire stacktrace. HTH!

```
stestr run --no-discover unit_tests.test_lib_charm_openstack_cinder_freenas::TestCinderFreeNASCharm::test_cinder_base                            [27/501]
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/subunit/run.py", line 149, in <module>
    main()
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/subunit/run.py", line 145, in main
    stdout=stdout, exit=False)
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/testtools/run.py", line 171, in __init__
    self.parseArgs(argv)
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/unittest2/main.py", line 135, in parseArgs
    self.createTests()
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/unittest2/main.py", line 142, in createTests
    self.module)
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/unittest2/loader.py", line 245, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/unittest2/loader.py", line 245, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/unittest2/loader.py", line 230, in loadTestsFromName
    test = obj()
TypeError: test_cinder_base() missing 1 required positional argument: 'self'
min() arg is an empty sequence                                                                                                                                                       Traceback (most recent call last):
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/cliff/app.py", line 401, in run_subcommand                                            result = cmd.run(parsed_args)
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/cliff/command.py", line 184, in run
    return_code = self.take_action(parsed_args) or 0
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/stestr/commands/run.py", line 213, in take_action
    suppress_attachments=suppress_attachments)
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/stestr/commands/run.py", line 366, in run_command
    return run_tests()
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/stestr/commands/run.py", line 363, in run_tests
    suppress_attachments=suppress_attachments)
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/stestr/commands/load.py", line 209, in load
    color, stdout, abbreviate, suppress_attachments)
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/stestr/commands/load.py", line 251, in _load_case
    start_time = min(start_times)
ValueError: min() arg is an empty sequence
Traceback (most recent call last):
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/bin/stestr", line 10, in <module>
    sys.exit(main())
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/stestr/cli.py", line 111, in main
    return cli.run(argv)
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/cliff/app.py", line 281, in run
    result = self.run_subcommand(remainder)
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/cliff/app.py", line 401, in run_subcommand
    result = cmd.run(parsed_args)
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/cliff/command.py", line 184, in run
    return_code = self.take_action(parsed_args) or 0                                                                                                                                   File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/stestr/commands/run.py", line 213, in take_action
    suppress_attachments=suppress_attachments)                                                                                                                                         File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/stestr/commands/run.py", line 366, in run_command
    return run_tests()
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/stestr/commands/run.py", line 363, in run_tests
    suppress_attachments=suppress_attachments)
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/stestr/commands/load.py", line 209, in load
    color, stdout, abbreviate, suppress_attachments)
  File "/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/lib/python3.6/site-packages/stestr/commands/load.py", line 251, in _load_case
    start_time = min(start_times)
ValueError: min() arg is an empty sequence
ERROR: InvocationError: '/home/multipass/src/review.opendev.org/cinder-freenas/.tox/py3/bin/stestr run --no-discover unit_tests.test_lib_charm_openstack_cinder_freenas::TestCinderFr
eeNASCharm::test_cinder_base'
```

**Comment by mtreinish** [comment]
I just pushed #255 which will fix the stestr issue reported here (which is the `ValueError: min()` stacktrace). The first stacktrace is actually the same thing I was hitting and is caused by bug in unittest2 when using a test class based off of unittest (instead of testtools or unittest2). I pushed up https://github.com/testing-cabal/testtools/pull/277 to address it, but that will probably be a while until it merges (if it does at all).

**Comment by mtreinish** [comment]
#256 will fix the issue outside of stestr currently. To address the first stack trace which was coming from unittest2 `TypeError: missing 1 required positional argument: 'self'` I wrote a separate test runner for stestr use that is based on stdlib unittest instead of using unittest2 or testtools. This will both fix the other half of the issue and actually have stestr own more of execution of the tests up until stdlib unittest is called (which should hopefully make it easier to address bugs like this in the future).
