### ISSUE TITLE
stestr run fails with stestr: 'run' is not a stestr command. See 'stestr --help'. with Python 3.10

### ISSUE THREAD

**Issue by elfosardo** [mtreinish/stestr#313]
**Issue description**
When running stestr run with Python 3.10 the command fails with the error:
stestr: 'run' is not a stestr command. See 'stestr --help'.

**Steps to reproduce the problem**
Install stestr in a virtualenv with python 3.10 or use stestr with python 3.10 as default python version
Try to launch stestr run

**System information**
 - OS: Fedora 34
 - stestr version: 3.2.0
 - Python release: Python 3.10

**Comment by mtreinish** [comment]
I dug into this. It looks like the underlying issue is caused by testtools (specifically it's use of unittest2) not being compatible with 3.10:

```
Traceback (most recent call last):
  File "/home/mtreinish/git/stestr/stestr/commands/run.py", line 25, in <module>
    import subunit
  File "/home/mtreinish/git/stestr/.tox/py310/lib/python3.10/site-packages/subunit/__init__.py", line 130, in <module>
    from testtools import content, content_type, ExtendedToOriginalDecorator
  File "/home/mtreinish/git/stestr/.tox/py310/lib/python3.10/site-packages/testtools/__init__.py", line 71, in <module>
    from testtools.testcase import (
  File "/home/mtreinish/git/stestr/.tox/py310/lib/python3.10/site-packages/testtools/testcase.py", line 33, in <module>
    import unittest2 as unittest
  File "/home/mtreinish/git/stestr/.tox/py310/lib/python3.10/site-packages/unittest2/__init__.py", line 40, in <module>
    from unittest2.collector import collector
  File "/home/mtreinish/git/stestr/.tox/py310/lib/python3.10/site-packages/unittest2/collector.py", line 3, in <module>
    from unittest2.loader import defaultTestLoader
  File "/home/mtreinish/git/stestr/.tox/py310/lib/python3.10/site-packages/unittest2/loader.py", line 13, in <module>
    from unittest2 import case, suite, util
  File "/home/mtreinish/git/stestr/.tox/py310/lib/python3.10/site-packages/unittest2/case.py", line 18, in <module>
    from unittest2 import result
  File "/home/mtreinish/git/stestr/.tox/py310/lib/python3.10/site-packages/unittest2/result.py", line 10, in <module>
    from unittest2.compatibility import wraps
  File "/home/mtreinish/git/stestr/.tox/py310/lib/python3.10/site-packages/unittest2/compatibility.py", line 143, in <module>
    class ChainMap(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

This should be fixed on the development branch for testtools already by: https://github.com/testing-cabal/testtools/pull/277 and will be fixed by the next testtools release.

**Comment by elfosardo** [comment]
@mtreinish thanks for your reply, I'll give it a try with the dev branch of testtools

**Comment by elfosardo** [comment]
@mtreinish that seems to do the trick, thanks!
I'll close this as it's not strictly on stestr and it has a fix on testtools, even if it's just in the dev branch for now
