### ISSUE TITLE
Stestr does not work with python-subunit 1.4.3 and testtools 2.6.0

### ISSUE THREAD

**Issue by pshchelo** [mtreinish/stestr#347]
**Issue description**
Testtools 2.6.0 dropped 'extras' dependency https://github.com/testing-cabal/testtools/commit/5d3b595e0dc23019d28d8b27e9039ac65278fc93.
At the same time, stestr is importing from extras w/o declaring it as a dependency https://github.com/mtreinish/stestr/blob/0f9a6deafebe4caf967375bc1456afa7041f3653/stestr/testlist.py#L17 which is now broken.

**Steps to reproduce the problem**
Install stestr in a clean virtualenv
```
❯ pip install stestr
...
Successfully installed PrettyTable-3.9.0 PyYAML-6.0.1 attrs-23.1.0 autopage-0.5.1 cliff-4.3.0 cmd2-2.4.3 fixtures-4.1.0 future-0.18.3 importlib-metadata-6.8.0 iso8601-2.0.0 pbr-5.11.1 pyperclip-1.8.2 python-subunit-1.4.3 stestr-4.0.1 stevedore-5.1.0 testtools-2.6.0 voluptuous-0.13.1 wcwidth-0.2.6 zipp-3.16.2

❯ python -c 'from stestr import commands'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/.virtualenvs/sandbox/lib/python3.10/site-packages/stestr/commands/__init__.py", line 19, in <module>
    from stestr.commands.list import list_command
  File "/home/ubuntu/.virtualenvs/sandbox/lib/python3.10/site-packages/stestr/commands/list.py", line 21, in <module>
    from stestr import config_file
  File "/home/ubuntu/.virtualenvs/sandbox/lib/python3.10/site-packages/stestr/config_file.py", line 20, in <module>
    from stestr import test_processor
  File "/home/ubuntu/.virtualenvs/sandbox/lib/python3.10/site-packages/stestr/test_processor.py", line 27, in <module>
    from stestr import testlist
  File "/home/ubuntu/.virtualenvs/sandbox/lib/python3.10/site-packages/stestr/testlist.py", line 17, in <module>
    from extras import try_import
ModuleNotFoundError: No module named 'extras'
```
**Specifications like the version of the project, operating system, or hardware**

**System information**
 - OS: Ubuntu 22.04
 - stestr version (`stestr --version`): 4.0.1
 - Python release (`python --version`): 3.10.12
 - pip packages (`pip freeze`): appdirs==1.4.4
attrs==23.1.0
autopage==0.5.1
cliff==4.3.0
cmd2==2.4.3
fixtures==4.1.0
future==0.18.3
importlib-metadata==6.8.0
iso8601==2.0.0
packaging==21.3
pbr==5.11.1
prettytable==3.9.0
pyparsing==3.0.9
pyperclip==1.8.2
python-subunit==1.4.3
PyYAML==6.0.1
six==1.16.0
stestr==4.0.1
stevedore==5.1.0
testtools==2.6.0
voluptuous==0.13.1
wcwidth==0.2.6
zipp==3.16.2

**Additional information**

**Comment by pshchelo** [comment]
In fact probably what broke things exactly now is new python-subunit - 1.4.3 was released yesterday that also dropped 'extras' dependency.
I updated issue title accordingly.
