### ISSUE TITLE
FAIL: stestr.tests.test_return_codes.TestReturnCodesToxIni.test_no_repo_dir on `python 3.12.2`

### ISSUE THREAD

**Issue by masayukig** [mtreinish/stestr#362]
**Issue description**

When I run stestr tests, these tests fail everytime.
```
$ stestr failing
======================================================================
FAIL: stestr.tests.test_return_codes.TestReturnCodesToxIni.test_no_repo_dir
tags: worker-5
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/migawa/git/stestr/stestr/tests/test_return_codes.py", line 233, in test_no_repo_dir
    self.assertRunExit("stestr run passing", 0)
  File "/home/migawa/git/stestr/stestr/tests/test_return_codes.py", line 99, in assertRunExit
    self.assertEqual(
  File "/home/migawa/.local/lib/python3.12/site-packages/testtools/testcase.py", line 395, in assertEqual
    self.assertThat(observed, matcher, message)
  File "/home/migawa/.local/lib/python3.12/site-packages/testtools/testcase.py", line 482, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: 1 != 0: Stdout: b''; Stderr: b'module \'configparser\' has no attribute \'SafeConfigParser\'\nTraceback (most recent call last):\n  File "/home/migawa/git/stestr/stestr/repository/file.py", line 60, in open\n    stream = open(os.path.join(base, "format"))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: \'/tmp/stestr-unit8d7f9bd_/.stestr/format\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/migawa/git/stestr/stestr/commands/run.py", line 470, in run_command\n    repo = util.get_repo_open(repo_url=repo_url)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/migawa/git/stestr/stestr/repository/util.py", line 45, in get_repo_open\n    return repo_module.RepositoryFactory().open(repo_url)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/migawa/git/stestr/stestr/repository/file.py", line 63, in open\n    raise repository.RepositoryNotFound(url)\nstestr.repository.abstract.RepositoryNotFound: No repository found in /tmp/stestr-unit8d7f9bd_. Create one by running "stestr init".\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/migawa/.local/lib/python3.12/site-packages/cliff/app.py", line 410, in run_subcommand\n    result = cmd.run(parsed_args)\n             ^^^^^^^^^^^^^^^^^^^^\n  File "/home/migawa/.local/lib/python3.12/site-packages/cliff/command.py", line 181, in run\n    return_code = self.take_action(parsed_args) or 0\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/migawa/git/stestr/stestr/commands/run.py", line 309, in take_action\n    result = run_command(\n             ^^^^^^^^^^^^\n  File "/home/migawa/git/stestr/stestr/commands/run.py", line 476, in run_command\n    tox_conf = configparser.SafeConfigParser()\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: module \'configparser\' has no attribute \'SafeConfigParser\'. Did you mean: \'RawConfigParser\'?\n'
======================================================================
FAIL: stestr.tests.test_return_codes.TestReturnCodesToxIni.test_empty_repo_dir
tags: worker-2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/migawa/git/stestr/stestr/tests/test_return_codes.py", line 240, in test_empty_repo_dir
    self.assertRunExit("stestr run passing", 0)
  File "/home/migawa/git/stestr/stestr/tests/test_return_codes.py", line 99, in assertRunExit
    self.assertEqual(
  File "/home/migawa/.local/lib/python3.12/site-packages/testtools/testcase.py", line 395, in assertEqual
    self.assertThat(observed, matcher, message)
  File "/home/migawa/.local/lib/python3.12/site-packages/testtools/testcase.py", line 482, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError: 1 != 0: Stdout: b''; Stderr: b'module \'configparser\' has no attribute \'SafeConfigParser\'\nTraceback (most recent call last):\n  File "/home/migawa/git/stestr/stestr/repository/file.py", line 60, in open\n    stream = open(os.path.join(base, "format"))\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: \'/tmp/stestr-unitldbt_6m6/.stestr/format\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/migawa/git/stestr/stestr/commands/run.py", line 470, in run_command\n    repo = util.get_repo_open(repo_url=repo_url)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/migawa/git/stestr/stestr/repository/util.py", line 45, in get_repo_open\n    return repo_module.RepositoryFactory().open(repo_url)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/migawa/git/stestr/stestr/repository/file.py", line 63, in open\n    raise repository.RepositoryNotFound(url)\nstestr.repository.abstract.RepositoryNotFound: No repository found in /tmp/stestr-unitldbt_6m6. Create one by running "stestr init".\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/migawa/.local/lib/python3.12/site-packages/cliff/app.py", line 410, in run_subcommand\n    result = cmd.run(parsed_args)\n             ^^^^^^^^^^^^^^^^^^^^\n  File "/home/migawa/.local/lib/python3.12/site-packages/cliff/command.py", line 181, in run\n    return_code = self.take_action(parsed_args) or 0\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/migawa/git/stestr/stestr/commands/run.py", line 309, in take_action\n    result = run_command(\n             ^^^^^^^^^^^^\n  File "/home/migawa/git/stestr/stestr/commands/run.py", line 476, in run_command\n    tox_conf = configparser.SafeConfigParser()\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: module \'configparser\' has no attribute \'SafeConfigParser\'. Did you mean: \'RawConfigParser\'?\n'
Ran 2 tests in 6.935s
FAILED (id=5, failures=2)
```

**Expected behavior and actual behavior**
Expected: No failures
Actual: 

**Steps to reproduce the problem**
`stestr run` on the environment like below.

**Specifications like the version of the project, operating system, or hardware**

**System information**
 - OS: Fedora 39
 - stestr version (`stestr --version`): `stestr 4.0.1.dev15`
 - Python release (`python --version`): `Python 3.12.2`
 - pip packages (`pip freeze`): 
```
$ pip freeze
alabaster==0.7.16
ansible==9.3.0
ansible-core==2.16.4
argcomplete==2.0.0
attrs==23.2.0
autopage==0.5.2
Babel==2.14.0
bcrypt==4.0.1
Beaker==1.12.1
beautifulsoup4==4.12.3
boto3==1.34.47
botocore==1.34.47
Brlapi==0.8.5
cachetools==5.3.3
cattrs==23.2.3
ceph==1.0.0
cephfs==2.0.0
cffi==1.15.1
chardet==5.2.0
charset-normalizer==3.2.0
click==8.1.3
cliff==4.6.0
cmd2==2.4.3
colorama==0.4.6
cryptography==41.0.7
csscompressor==0.9.5
cupshelpers==1.0
dbus-python==1.3.2
ddt==1.7.2
decorator==5.1.1
defusedxml==0.7.1
diff-highlight==1.2.0
distlib==0.3.8
distro==1.8.0
dnf==4.19.2
docutils==0.20.1
dropbox==11.36.2
duplicity==2.1.5
esbonio==0.16.4
extras==1.0.0
fasteners==0.19
fedora-third-party==0.10
file-magic==0.4.0
filelock==3.13.3
fixtures==4.1.0
fros==1.1
ghp-import==2.1.0
google-api-core==2.11.1
google-api-python-client==2.120.0
google-auth==2.28.2
google-auth-httplib2==0.2.0
googleapis-common-protos==1.63.0
grpcio==1.48.4
grpcio-status==1.48.4
gssapi==1.7.3
htmlmin2==0.1.13
httplib2==0.21.0
humanize==3.13.1
idna==3.4
imagesize==1.4.1
iso8601==2.1.0
Jinja2==3.1.3
jmespath==1.0.1
jsmin==3.0.1
koji==1.34.0
langtable==0.0.65
libcomps==0.1.20
libdnf==0.73.1
libdnf5==5.1.15
libvirt-python==9.7.0
lsprotocol==2023.0.1
lxml==4.9.3
Mako==1.2.3
Markdown==3.6
MarkupSafe==2.1.3
mergedeep==1.3.4
mkdocs==1.5.3
mkdocs-material==9.5.16
mkdocs-material-extensions==1.3.1
mkdocs-minify-plugin==0.8.0
nftables==0.1
oauth2client==4.1.3
olefile==0.46
packaging==24.0
paginate==0.5.6
paramiko==3.4.0
Paste==3.5.3
pathspec==0.12.1
pbr==6.0.0
pexpect==4.8.0
pillow==10.2.0
platformdirs==4.2.0
pluggy==1.4.0
ply==3.11
prettytable==3.6.0
protobuf==3.19.6
ptyprocess==0.7.0
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycairo==1.25.1
pycparser==2.20
pycrypto==2.6.1
pycups==2.0.1
pycurl==7.45.2
PyDrive2==1.19.0
pyenchant==3.2.2
pygls==1.3.1
Pygments==2.17.2
PyGObject==3.46.0
pymdown-extensions==10.7.1
PyNaCl==1.5.0
pyOpenSSL==23.2.0
pyparsing==3.0.9
pyperclip==1.8.2
pyproject-api==1.6.1
PySocks==1.7.1
pyspellchecker==0.8.1
python-augeas==1.1.0
python-dateutil==2.8.2
python-subunit==1.4.4
pyxdg==0.27
PyYAML==6.0.1
pyyaml_env_tag==0.1
rados==2.0.0
rbd==2.0.0
regex==2023.12.25
requests==2.28.2
requests-gssapi==1.2.3
resolvelib==0.5.5
rgw==2.0.0
rpm==4.19.1.1
rsa==4.9
s3transfer==0.10.1
selinux @ file:///builddir/build/BUILD/libselinux-3.5/src
sepolicy @ file:///builddir/build/BUILD/selinux-3.5/python/sepolicy
setools==4.4.3
setuptools==67.7.2
simpleaudio==1.0.4
six==1.16.0
snowballstemmer==2.2.0
sos==4.6.0
soupsieve==2.5
Sphinx==7.2.6
sphinxcontrib-applehelp==1.0.8
sphinxcontrib-devhelp==1.0.6
sphinxcontrib-htmlhelp==2.0.5
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.7
sphinxcontrib-serializinghtml==1.1.10
SSSDConfig==2.9.4
-e git+ssh://git@github.com/masayukig/stestr.git@d1ebe008e4251b9786a89a6cd9ee8445c6db772d#egg=stestr
stevedore==5.2.0
stone==3.2.1
subunit==0.0.0a0
systemd-python==235
Tempita==0.5.2
testtools==2.7.1
tomlkit==0.12.4
tox==4.12.1
uritemplate==4.1.1
urllib3==1.26.18
virtualenv==20.25.1
voluptuous==0.14.2
watchdog==4.0.0
wcwidth==0.2.5
```

**Additional information**
I'm facing two failures on `stestr.tests.test_return_codes.TestReturnCodesToxIni.test_no_repo_dir` and `stestr.tests.test_return_codes.TestReturnCodesToxIni.test_empty_repo_dir`. And it seems that the same error happens in both tests.

This issue doesn't happen on `python 3.11.8` on my environment(Fedora39) somehow.
```
$ python --version
Python 3.11.8
$ stestr --version
stestr 4.0.1.dev14
$ stestr failing
PASSED (id=13)
```

**Comment by jelly** [comment]
On Arch Linux with 3.12 we get:
```
stestr.tests.test_return_codes.TestReturnCodesToxIni.test_history_empty
-----------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/build/python-stestr/src/stestr-4.1.0/stestr/tests/test_return_codes.py", line 336, in test_history_empty
    self.assertEqual("", "\n".join([x.rstrip() for x in table.split("\n")]).strip())

      File "/usr/lib/python3.12/site-packages/testtools/testcase.py", line 395, in assertEqual
    self.assertThat(observed, matcher, message)

      File "/usr/lib/python3.12/site-packages/testtools/testcase.py", line 482, in assertThat
    raise mismatch_error

    testtools.matchers._impl.MismatchError: '' != '"Run ID","Passed","Runtime","Date"'


stestr.tests.test_return_codes.TestReturnCodesToxIni.test_history_list
----------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/build/python-stestr/src/stestr-4.1.0/stestr/tests/test_return_codes.py", line 321, in test_history_list
    self.assertIn("| 0      | True   |", table.split("\n")[3].rstrip())

      File "/usr/lib/python3.12/site-packages/testtools/testcase.py", line 401, in assertIn
    self.assertThat(haystack, Contains(needle), message)

      File "/usr/lib/python3.12/site-packages/testtools/testcase.py", line 482, in assertThat
    raise mismatch_error

    testtools.matchers._impl.MismatchError: '| 0      | True   |' not in '"2",True,"0.000670s","2024-04-09 18:35:50.974916+00:00"'
```
